# Generated by ariadne-codegen
# Source: src/graphql/operations

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class BusinessByName(BaseModel):
    business_by_name: Optional["BusinessByNameBusinessByName"] = Field(
        alias="businessByName"
    )


class BusinessByNameBusinessByName(BaseModel):
    id: str
    name: str
    description: Optional[str]


BusinessByName.model_rebuild()
