# Generated by ariadne-codegen
# Source: src/graphql/operations

from typing import List, Optional

from .base_model import BaseModel


class Businesses(BaseModel):
    businesses: List["BusinessesBusinesses"]


class BusinessesBusinesses(BaseModel):
    id: str
    name: str
    description: Optional[str]


Businesses.model_rebuild()
