# Generated by ariadne-codegen
# Source: src/graphql/operations

from typing import List, Optional

from .base_model import BaseModel


class Business(BaseModel):
    business: Optional["BusinessBusiness"]


class BusinessBusiness(BaseModel):
    id: str
    name: str
    description: Optional[str]
    website: Optional[str]
    products: Optional[List["BusinessBusinessProducts"]]
    executives: Optional[List["BusinessBusinessExecutives"]]
    owners: Optional[List["BusinessBusinessOwners"]]


class BusinessBusinessProducts(BaseModel):
    id: str
    name: str
    description: Optional[str]


class BusinessBusinessExecutives(BaseModel):
    role: Optional[str]
    title: Optional[str]
    person: "BusinessBusinessExecutivesPerson"


class BusinessBusinessExecutivesPerson(BaseModel):
    id: str
    name: str


class BusinessBusinessOwners(BaseModel):
    id: str
    name: str


Business.model_rebuild()
BusinessBusiness.model_rebuild()
BusinessBusinessExecutives.model_rebuild()
