# Generated by ariadne-codegen
# Source: src/graphql/operations

from typing import List

from pydantic import Field

from .base_model import BaseModel


class CaseStudies(BaseModel):
    case_studies: List["CaseStudiesCaseStudies"] = Field(alias="caseStudies")


class CaseStudiesCaseStudies(BaseModel):
    id: str
    title: str
    summary: str


CaseStudies.model_rebuild()
