# Generated by ariadne-codegen
# Source: src/graphql/operations

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class CaseStudy(BaseModel):
    case_study: Optional["CaseStudyCaseStudy"] = Field(alias="caseStudy")


class CaseStudyCaseStudy(BaseModel):
    id: str
    title: str
    summary: str


CaseStudy.model_rebuild()
