# Generated by ariadne-codegen
# Source: src/graphql/operations

from typing import Any, Dict, Optional, Union

from .async_base_client import AsyncBaseClient
from .base_model import UNSET, UnsetType
from .business import Business
from .businesses import Businesses
from .case_studies import CaseStudies
from .case_study import CaseStudy
from .compound import Compound
from .compounds import Compounds
from .create_business import CreateBusiness
from .create_case_study import CreateCaseStudy
from .create_compound import CreateCompound
from .create_episode import CreateEpisode
from .create_person import CreatePerson
from .create_product import CreateProduct
from .episode import Episode
from .episodes import Episodes
from .input_types import (
    BusinessCreateWithIdsInput,
    BusinessUpdateRelationFieldsInput,
    BusinessUpdateWithIdsInput,
    CaseStudyCreateWithOptionalIdsInput,
    CaseStudyUpdateWithOptionalIdsInput,
    CompoundCreateWithIdsInput,
    CompoundUpdateRelationFieldsInput,
    CompoundUpdateWithIdsInput,
    EpisodeCreateWithIdsInput,
    EpisodeUpdateRelationFieldsInput,
    EpisodeUpdateWithIdsInput,
    PersonCreateWithIdsInput,
    PersonUpdateRelationFieldsInput,
    PersonUpdateWithIdsInput,
    ProductCreateWithIdsInput,
    ProductUpdateRelationFieldsInput,
    ProductUpdateWithIdsInput,
)
from .people import People
from .person import Person
from .product import Product
from .products import Products
from .update_business import UpdateBusiness
from .update_business_relations import UpdateBusinessRelations
from .update_case_study import UpdateCaseStudy
from .update_compound import UpdateCompound
from .update_compound_relations import UpdateCompoundRelations
from .update_episode import UpdateEpisode
from .update_episode_relations import UpdateEpisodeRelations
from .update_person import UpdatePerson
from .update_person_relations import UpdatePersonRelations
from .update_product import UpdateProduct
from .update_product_relations import UpdateProductRelations


def gql(q: str) -> str:
    return q


class Client(AsyncBaseClient):
    async def create_business(
        self, input: BusinessCreateWithIdsInput, **kwargs: Any
    ) -> CreateBusiness:
        query = gql(
            """
            mutation CreateBusiness($input: BusinessCreateWithIdsInput!) {
              createBusiness(input: $input) {
                id
                name
                description
              }
            }
            """
        )
        variables: Dict[str, object] = {"input": input}
        response = await self.execute(
            query=query, operation_name="CreateBusiness", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return CreateBusiness.model_validate(data)

    async def update_business(
        self, input: BusinessUpdateWithIdsInput, **kwargs: Any
    ) -> UpdateBusiness:
        query = gql(
            """
            mutation UpdateBusiness($input: BusinessUpdateWithIdsInput!) {
              updateBusiness(input: $input) {
                id
                name
                description
              }
            }
            """
        )
        variables: Dict[str, object] = {"input": input}
        response = await self.execute(
            query=query, operation_name="UpdateBusiness", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return UpdateBusiness.model_validate(data)

    async def update_business_relations(
        self, input: BusinessUpdateRelationFieldsInput, **kwargs: Any
    ) -> UpdateBusinessRelations:
        query = gql(
            """
            mutation UpdateBusinessRelations($input: BusinessUpdateRelationFieldsInput!) {
              updateBusinessRelations(input: $input) {
                id
                name
              }
            }
            """
        )
        variables: Dict[str, object] = {"input": input}
        response = await self.execute(
            query=query,
            operation_name="UpdateBusinessRelations",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return UpdateBusinessRelations.model_validate(data)

    async def create_product(
        self, input: ProductCreateWithIdsInput, **kwargs: Any
    ) -> CreateProduct:
        query = gql(
            """
            mutation CreateProduct($input: ProductCreateWithIdsInput!) {
              createProduct(input: $input) {
                id
                name
                description
              }
            }
            """
        )
        variables: Dict[str, object] = {"input": input}
        response = await self.execute(
            query=query, operation_name="CreateProduct", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return CreateProduct.model_validate(data)

    async def update_product(
        self, input: ProductUpdateWithIdsInput, **kwargs: Any
    ) -> UpdateProduct:
        query = gql(
            """
            mutation UpdateProduct($input: ProductUpdateWithIdsInput!) {
              updateProduct(input: $input) {
                id
                name
                description
              }
            }
            """
        )
        variables: Dict[str, object] = {"input": input}
        response = await self.execute(
            query=query, operation_name="UpdateProduct", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return UpdateProduct.model_validate(data)

    async def update_product_relations(
        self, input: ProductUpdateRelationFieldsInput, **kwargs: Any
    ) -> UpdateProductRelations:
        query = gql(
            """
            mutation UpdateProductRelations($input: ProductUpdateRelationFieldsInput!) {
              updateProductRelations(input: $input) {
                id
                name
              }
            }
            """
        )
        variables: Dict[str, object] = {"input": input}
        response = await self.execute(
            query=query,
            operation_name="UpdateProductRelations",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return UpdateProductRelations.model_validate(data)

    async def create_person(
        self, input: PersonCreateWithIdsInput, **kwargs: Any
    ) -> CreatePerson:
        query = gql(
            """
            mutation CreatePerson($input: PersonCreateWithIdsInput!) {
              createPerson(input: $input) {
                id
                name
                role
              }
            }
            """
        )
        variables: Dict[str, object] = {"input": input}
        response = await self.execute(
            query=query, operation_name="CreatePerson", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return CreatePerson.model_validate(data)

    async def update_person(
        self, input: PersonUpdateWithIdsInput, **kwargs: Any
    ) -> UpdatePerson:
        query = gql(
            """
            mutation UpdatePerson($input: PersonUpdateWithIdsInput!) {
              updatePerson(input: $input) {
                id
                name
                role
              }
            }
            """
        )
        variables: Dict[str, object] = {"input": input}
        response = await self.execute(
            query=query, operation_name="UpdatePerson", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return UpdatePerson.model_validate(data)

    async def update_person_relations(
        self, input: PersonUpdateRelationFieldsInput, **kwargs: Any
    ) -> UpdatePersonRelations:
        query = gql(
            """
            mutation UpdatePersonRelations($input: PersonUpdateRelationFieldsInput!) {
              updatePersonRelations(input: $input) {
                id
                name
              }
            }
            """
        )
        variables: Dict[str, object] = {"input": input}
        response = await self.execute(
            query=query,
            operation_name="UpdatePersonRelations",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return UpdatePersonRelations.model_validate(data)

    async def create_episode(
        self, input: EpisodeCreateWithIdsInput, **kwargs: Any
    ) -> CreateEpisode:
        query = gql(
            """
            mutation CreateEpisode($input: EpisodeCreateWithIdsInput!) {
              createEpisode(input: $input) {
                id
                episodeTitle
                channelName
              }
            }
            """
        )
        variables: Dict[str, object] = {"input": input}
        response = await self.execute(
            query=query, operation_name="CreateEpisode", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return CreateEpisode.model_validate(data)

    async def update_episode(
        self, input: EpisodeUpdateWithIdsInput, **kwargs: Any
    ) -> UpdateEpisode:
        query = gql(
            """
            mutation UpdateEpisode($input: EpisodeUpdateWithIdsInput!) {
              updateEpisode(input: $input) {
                id
                episodeTitle
                channelName
              }
            }
            """
        )
        variables: Dict[str, object] = {"input": input}
        response = await self.execute(
            query=query, operation_name="UpdateEpisode", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return UpdateEpisode.model_validate(data)

    async def update_episode_relations(
        self, input: EpisodeUpdateRelationFieldsInput, **kwargs: Any
    ) -> UpdateEpisodeRelations:
        query = gql(
            """
            mutation UpdateEpisodeRelations($input: EpisodeUpdateRelationFieldsInput!) {
              updateEpisodeRelations(input: $input) {
                id
                episodeTitle
              }
            }
            """
        )
        variables: Dict[str, object] = {"input": input}
        response = await self.execute(
            query=query,
            operation_name="UpdateEpisodeRelations",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return UpdateEpisodeRelations.model_validate(data)

    async def create_compound(
        self, input: CompoundCreateWithIdsInput, **kwargs: Any
    ) -> CreateCompound:
        query = gql(
            """
            mutation CreateCompound($input: CompoundCreateWithIdsInput!) {
              createCompound(input: $input) {
                id
                name
                description
              }
            }
            """
        )
        variables: Dict[str, object] = {"input": input}
        response = await self.execute(
            query=query, operation_name="CreateCompound", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return CreateCompound.model_validate(data)

    async def update_compound(
        self, input: CompoundUpdateWithIdsInput, **kwargs: Any
    ) -> UpdateCompound:
        query = gql(
            """
            mutation UpdateCompound($input: CompoundUpdateWithIdsInput!) {
              updateCompound(input: $input) {
                id
                name
                description
              }
            }
            """
        )
        variables: Dict[str, object] = {"input": input}
        response = await self.execute(
            query=query, operation_name="UpdateCompound", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return UpdateCompound.model_validate(data)

    async def update_compound_relations(
        self, input: CompoundUpdateRelationFieldsInput, **kwargs: Any
    ) -> UpdateCompoundRelations:
        query = gql(
            """
            mutation UpdateCompoundRelations($input: CompoundUpdateRelationFieldsInput!) {
              updateCompoundRelations(input: $input) {
                id
                name
              }
            }
            """
        )
        variables: Dict[str, object] = {"input": input}
        response = await self.execute(
            query=query,
            operation_name="UpdateCompoundRelations",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return UpdateCompoundRelations.model_validate(data)

    async def create_case_study(
        self, input: CaseStudyCreateWithOptionalIdsInput, **kwargs: Any
    ) -> CreateCaseStudy:
        query = gql(
            """
            mutation CreateCaseStudy($input: CaseStudyCreateWithOptionalIdsInput!) {
              createCaseStudy(input: $input) {
                id
                title
                summary
              }
            }
            """
        )
        variables: Dict[str, object] = {"input": input}
        response = await self.execute(
            query=query, operation_name="CreateCaseStudy", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return CreateCaseStudy.model_validate(data)

    async def update_case_study(
        self, input: CaseStudyUpdateWithOptionalIdsInput, **kwargs: Any
    ) -> UpdateCaseStudy:
        query = gql(
            """
            mutation UpdateCaseStudy($input: CaseStudyUpdateWithOptionalIdsInput!) {
              updateCaseStudy(input: $input) {
                id
                title
                summary
              }
            }
            """
        )
        variables: Dict[str, object] = {"input": input}
        response = await self.execute(
            query=query, operation_name="UpdateCaseStudy", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return UpdateCaseStudy.model_validate(data)

    async def business(self, id: str, **kwargs: Any) -> Business:
        query = gql(
            """
            query Business($id: ID!) {
              business(id: $id) {
                id
                name
                description
                website
                products {
                  id
                  name
                  description
                }
                executives {
                  role
                  title
                  person {
                    id
                    name
                  }
                }
                owners {
                  id
                  name
                }
              }
            }
            """
        )
        variables: Dict[str, object] = {"id": id}
        response = await self.execute(
            query=query, operation_name="Business", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return Business.model_validate(data)

    async def businesses(
        self,
        limit: Union[Optional[int], UnsetType] = UNSET,
        offset: Union[Optional[int], UnsetType] = UNSET,
        **kwargs: Any
    ) -> Businesses:
        query = gql(
            """
            query Businesses($limit: Int, $offset: Int) {
              businesses(limit: $limit, offset: $offset) {
                id
                name
                description
              }
            }
            """
        )
        variables: Dict[str, object] = {"limit": limit, "offset": offset}
        response = await self.execute(
            query=query, operation_name="Businesses", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return Businesses.model_validate(data)

    async def product(self, id: str, **kwargs: Any) -> Product:
        query = gql(
            """
            query Product($id: ID!) {
              product(id: $id) {
                id
                name
                description
              }
            }
            """
        )
        variables: Dict[str, object] = {"id": id}
        response = await self.execute(
            query=query, operation_name="Product", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return Product.model_validate(data)

    async def products(
        self,
        limit: Union[Optional[int], UnsetType] = UNSET,
        offset: Union[Optional[int], UnsetType] = UNSET,
        **kwargs: Any
    ) -> Products:
        query = gql(
            """
            query Products($limit: Int, $offset: Int) {
              products(limit: $limit, offset: $offset) {
                id
                name
                description
              }
            }
            """
        )
        variables: Dict[str, object] = {"limit": limit, "offset": offset}
        response = await self.execute(
            query=query, operation_name="Products", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return Products.model_validate(data)

    async def person(self, id: str, **kwargs: Any) -> Person:
        query = gql(
            """
            query Person($id: ID!) {
              person(id: $id) {
                id
                name
                role
              }
            }
            """
        )
        variables: Dict[str, object] = {"id": id}
        response = await self.execute(
            query=query, operation_name="Person", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return Person.model_validate(data)

    async def people(
        self,
        limit: Union[Optional[int], UnsetType] = UNSET,
        offset: Union[Optional[int], UnsetType] = UNSET,
        **kwargs: Any
    ) -> People:
        query = gql(
            """
            query People($limit: Int, $offset: Int) {
              people(limit: $limit, offset: $offset) {
                id
                name
                role
              }
            }
            """
        )
        variables: Dict[str, object] = {"limit": limit, "offset": offset}
        response = await self.execute(
            query=query, operation_name="People", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return People.model_validate(data)

    async def compound(self, id: str, **kwargs: Any) -> Compound:
        query = gql(
            """
            query Compound($id: ID!) {
              compound(id: $id) {
                id
                name
                description
              }
            }
            """
        )
        variables: Dict[str, object] = {"id": id}
        response = await self.execute(
            query=query, operation_name="Compound", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return Compound.model_validate(data)

    async def compounds(
        self,
        limit: Union[Optional[int], UnsetType] = UNSET,
        offset: Union[Optional[int], UnsetType] = UNSET,
        **kwargs: Any
    ) -> Compounds:
        query = gql(
            """
            query Compounds($limit: Int, $offset: Int) {
              compounds(limit: $limit, offset: $offset) {
                id
                name
                description
              }
            }
            """
        )
        variables: Dict[str, object] = {"limit": limit, "offset": offset}
        response = await self.execute(
            query=query, operation_name="Compounds", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return Compounds.model_validate(data)

    async def case_study(self, id: str, **kwargs: Any) -> CaseStudy:
        query = gql(
            """
            query CaseStudy($id: ID!) {
              caseStudy(id: $id) {
                id
                title
                summary
              }
            }
            """
        )
        variables: Dict[str, object] = {"id": id}
        response = await self.execute(
            query=query, operation_name="CaseStudy", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return CaseStudy.model_validate(data)

    async def case_studies(
        self,
        limit: Union[Optional[int], UnsetType] = UNSET,
        offset: Union[Optional[int], UnsetType] = UNSET,
        **kwargs: Any
    ) -> CaseStudies:
        query = gql(
            """
            query CaseStudies($limit: Int, $offset: Int) {
              caseStudies(limit: $limit, offset: $offset) {
                id
                title
                summary
              }
            }
            """
        )
        variables: Dict[str, object] = {"limit": limit, "offset": offset}
        response = await self.execute(
            query=query, operation_name="CaseStudies", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return CaseStudies.model_validate(data)

    async def episode(self, id: str, **kwargs: Any) -> Episode:
        query = gql(
            """
            query Episode($id: ID!) {
              episode(id: $id) {
                id
                episodeTitle
                channelName
              }
            }
            """
        )
        variables: Dict[str, object] = {"id": id}
        response = await self.execute(
            query=query, operation_name="Episode", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return Episode.model_validate(data)

    async def episodes(
        self,
        limit: Union[Optional[int], UnsetType] = UNSET,
        offset: Union[Optional[int], UnsetType] = UNSET,
        **kwargs: Any
    ) -> Episodes:
        query = gql(
            """
            query Episodes($limit: Int, $offset: Int) {
              episodes(limit: $limit, offset: $offset) {
                id
                episodeTitle
                channelName
              }
            }
            """
        )
        variables: Dict[str, object] = {"limit": limit, "offset": offset}
        response = await self.execute(
            query=query, operation_name="Episodes", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return Episodes.model_validate(data)
