# Generated by ariadne-codegen
# Source: src/graphql/operations

from typing import Any

from .async_base_client import AsyncBaseClient
from .create_organization import CreateOrganization
from .get_organizations import GetOrganizations
from .input_types import (
    EvidenceEdgeInput,
    LinkResearchRunUsesPlanInput,
    OrganizationInput,
    OrganizationSearchInput,
    UpdateOrganizationInput,
    UpsertDocumentInput,
    UpsertDocumentTextVersionBundleInput,
    UpsertEvidenceEdgesInput,
    UpsertResearchPlanRefInput,
    UpsertResearchRunRefInput,
)
from .link_research_run_uses_plan import LinkResearchRunUsesPlan
from .search_organizations import SearchOrganizations
from .update_organization import UpdateOrganization
from .upsert_document import UpsertDocument
from .upsert_document_text_version_bundle import UpsertDocumentTextVersionBundle
from .upsert_evidence_edge import UpsertEvidenceEdge
from .upsert_evidence_edges import UpsertEvidenceEdges
from .upsert_research_plan_ref import UpsertResearchPlanRef
from .upsert_research_run_ref import UpsertResearchRunRef


def gql(q: str) -> str:
    return q


class Client(AsyncBaseClient):
    async def create_organization(
        self, input: OrganizationInput, **kwargs: Any
    ) -> CreateOrganization:
        query = gql(
            """
            mutation CreateOrganization($input: OrganizationInput!) {
              createOrganization(input: $input) {
                organizationId
                name
              }
            }
            """
        )
        variables: dict[str, object] = {"input": input}
        response = await self.execute(
            query=query,
            operation_name="CreateOrganization",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return CreateOrganization.model_validate(data)

    async def update_organization(
        self, input: UpdateOrganizationInput, **kwargs: Any
    ) -> UpdateOrganization:
        query = gql(
            """
            mutation UpdateOrganization($input: UpdateOrganizationInput!) {
              updateOrganization(input: $input) {
                organizationId
                name
                aliases
                orgType
              }
            }
            """
        )
        variables: dict[str, object] = {"input": input}
        response = await self.execute(
            query=query,
            operation_name="UpdateOrganization",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return UpdateOrganization.model_validate(data)

    async def upsert_research_plan_ref(
        self, input: UpsertResearchPlanRefInput, **kwargs: Any
    ) -> UpsertResearchPlanRef:
        query = gql(
            """
            mutation UpsertResearchPlanRef($input: UpsertResearchPlanRefInput!) {
              upsertResearchPlanRef(input: $input) {
                researchPlanRefId
                mongoPlanId
                label
                version
                validAt
                invalidAt
                expiredAt
                createdAt
                updatedAt
              }
            }
            """
        )
        variables: dict[str, object] = {"input": input}
        response = await self.execute(
            query=query,
            operation_name="UpsertResearchPlanRef",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return UpsertResearchPlanRef.model_validate(data)

    async def upsert_research_run_ref(
        self, input: UpsertResearchRunRefInput, **kwargs: Any
    ) -> UpsertResearchRunRef:
        query = gql(
            """
            mutation UpsertResearchRunRef($input: UpsertResearchRunRefInput!) {
              upsertResearchRunRef(input: $input) {
                researchRunRefId
                mongoRunId
                label
                startedAt
                endedAt
                validAt
                invalidAt
                expiredAt
                createdAt
                updatedAt
                usesPlan {
                  researchPlanRef {
                    researchPlanRefId
                    mongoPlanId
                    label
                    version
                    validAt
                    invalidAt
                    expiredAt
                    createdAt
                    updatedAt
                  }
                  validAt
                  invalidAt
                  expiredAt
                  createdAt
                }
              }
            }
            """
        )
        variables: dict[str, object] = {"input": input}
        response = await self.execute(
            query=query,
            operation_name="UpsertResearchRunRef",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return UpsertResearchRunRef.model_validate(data)

    async def link_research_run_uses_plan(
        self, input: LinkResearchRunUsesPlanInput, **kwargs: Any
    ) -> LinkResearchRunUsesPlan:
        query = gql(
            """
            mutation LinkResearchRunUsesPlan($input: LinkResearchRunUsesPlanInput!) {
              linkResearchRunUsesPlan(input: $input) {
                researchRunRefId
                mongoRunId
                label
                startedAt
                endedAt
                validAt
                invalidAt
                expiredAt
                createdAt
                updatedAt
                usesPlan {
                  researchPlanRef {
                    researchPlanRefId
                    mongoPlanId
                    label
                    version
                    validAt
                    invalidAt
                    expiredAt
                    createdAt
                    updatedAt
                  }
                  validAt
                  invalidAt
                  expiredAt
                  createdAt
                }
              }
            }
            """
        )
        variables: dict[str, object] = {"input": input}
        response = await self.execute(
            query=query,
            operation_name="LinkResearchRunUsesPlan",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return LinkResearchRunUsesPlan.model_validate(data)

    async def upsert_document(
        self, input: UpsertDocumentInput, **kwargs: Any
    ) -> UpsertDocument:
        query = gql(
            """
            mutation UpsertDocument($input: UpsertDocumentInput!) {
              upsertDocument(input: $input) {
                documentId
                documentKey
                type
                title
                url
                publishedAt
                retrievedAt
                validAt
                invalidAt
                expiredAt
                createdAt
                updatedAt
                searchText
                searchTextEmbedding
                searchTextModel
                searchTextVersion
                searchTextUpdatedAt
                hasTextVersion {
                  documentTextVersion {
                    documentTextVersionId
                    textVersionHash
                    source
                    language
                    text
                    validAt
                    invalidAt
                    expiredAt
                    createdAt
                    updatedAt
                    searchText
                    searchTextEmbedding
                    searchTextModel
                    searchTextVersion
                    searchTextUpdatedAt
                  }
                  validAt
                  invalidAt
                  expiredAt
                  createdAt
                }
                chunks {
                  chunk {
                    chunkId
                    chunkKey
                    index
                    text
                    charStart
                    charEnd
                    startMs
                    endMs
                    embedding
                    embeddingModel
                    embeddingVersion
                    validAt
                    invalidAt
                    expiredAt
                    createdAt
                    updatedAt
                  }
                  validAt
                  invalidAt
                  expiredAt
                  createdAt
                }
                generatedBy {
                  researchRunRef {
                    researchRunRefId
                    mongoRunId
                    label
                    startedAt
                    endedAt
                    validAt
                    invalidAt
                    expiredAt
                    createdAt
                    updatedAt
                  }
                  operation
                  stageKey
                  subStageKey
                  extractorVersion
                  extractedAt
                  validAt
                  invalidAt
                  expiredAt
                  createdAt
                }
              }
            }
            """
        )
        variables: dict[str, object] = {"input": input}
        response = await self.execute(
            query=query, operation_name="UpsertDocument", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return UpsertDocument.model_validate(data)

    async def upsert_document_text_version_bundle(
        self, input: UpsertDocumentTextVersionBundleInput, **kwargs: Any
    ) -> UpsertDocumentTextVersionBundle:
        query = gql(
            """
            mutation UpsertDocumentTextVersionBundle($input: UpsertDocumentTextVersionBundleInput!) {
              upsertDocumentTextVersionBundle(input: $input) {
                documentId
                documentTextVersionId
                segmentationId
                chunkMetas {
                  chunkId
                  chunkKey
                  index
                }
                nextChunkEdgesCreated
              }
            }
            """
        )
        variables: dict[str, object] = {"input": input}
        response = await self.execute(
            query=query,
            operation_name="UpsertDocumentTextVersionBundle",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return UpsertDocumentTextVersionBundle.model_validate(data)

    async def upsert_evidence_edge(
        self, input: EvidenceEdgeInput, **kwargs: Any
    ) -> UpsertEvidenceEdge:
        query = gql(
            """
            mutation UpsertEvidenceEdge($input: EvidenceEdgeInput!) {
              upsertEvidenceEdge(input: $input) {
                ok
                edgeType
                relKey
                relationshipId
                source {
                  __typename
                  ... on EvidenceSourceRefDocumentResult {
                    kind
                    documentId
                  }
                  ... on EvidenceSourceRefChunkResult {
                    kind
                    chunkId
                  }
                }
                target {
                  nodeId
                  label
                  uniqueKey
                  uniqueKeyValue
                }
                created
                updated
              }
            }
            """
        )
        variables: dict[str, object] = {"input": input}
        response = await self.execute(
            query=query,
            operation_name="UpsertEvidenceEdge",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return UpsertEvidenceEdge.model_validate(data)

    async def upsert_evidence_edges(
        self, input: list[UpsertEvidenceEdgesInput], **kwargs: Any
    ) -> UpsertEvidenceEdges:
        query = gql(
            """
            mutation UpsertEvidenceEdges($input: [UpsertEvidenceEdgesInput!]!) {
              upsertEvidenceEdges(input: $input) {
                ok
                counts {
                  received
                  attempted
                  created
                  updated
                  failed
                }
                results {
                  ok
                  edgeType
                  relKey
                  relationshipId
                  source {
                    __typename
                    ... on EvidenceSourceRefDocumentResult {
                      kind
                      documentId
                    }
                    ... on EvidenceSourceRefChunkResult {
                      kind
                      chunkId
                    }
                  }
                  target {
                    nodeId
                    label
                    uniqueKey
                    uniqueKeyValue
                  }
                  created
                  updated
                }
                errors {
                  index
                  edgeType
                  message
                  code
                }
              }
            }
            """
        )
        variables: dict[str, object] = {"input": input}
        response = await self.execute(
            query=query,
            operation_name="UpsertEvidenceEdges",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return UpsertEvidenceEdges.model_validate(data)

    async def get_organizations(self, **kwargs: Any) -> GetOrganizations:
        query = gql(
            """
            query GetOrganizations {
              organizations {
                organizationId
                name
                aliases
                orgType
              }
            }
            """
        )
        variables: dict[str, object] = {}
        response = await self.execute(
            query=query,
            operation_name="GetOrganizations",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return GetOrganizations.model_validate(data)

    async def search_organizations(
        self, input: OrganizationSearchInput, **kwargs: Any
    ) -> SearchOrganizations:
        query = gql(
            """
            query SearchOrganizations($input: OrganizationSearchInput!) {
              searchOrganizations(input: $input) {
                items {
                  node {
                    organizationId
                    name
                  }
                  score
                  reasons {
                    kind
                    field
                    value
                    score
                    detail
                  }
                }
                pageInfo {
                  hasNextPage
                  endCursor
                }
              }
            }
            """
        )
        variables: dict[str, object] = {"input": input}
        response = await self.execute(
            query=query,
            operation_name="SearchOrganizations",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return SearchOrganizations.model_validate(data)
