# Generated by ariadne-codegen
# Source: src/graphql/operations

from typing import Any, Optional, Union

from .async_base_client import AsyncBaseClient
from .base_model import UNSET, UnsetType
from .business import Business
from .business_by_name import BusinessByName
from .businesses import Businesses
from .case_studies import CaseStudies
from .case_study import CaseStudy
from .compound import Compound
from .compound_by_name import CompoundByName
from .compounds import Compounds
from .episode import Episode
from .episode_by_page_url import EpisodeByPageUrl
from .episodes import Episodes
from .input_types import (
    BusinessUpsertRelationFieldsInput,
    EpisodeUpdateRelationFieldsInput,
    ProductUpsertRelationFieldsInput,
)
from .login import Login
from .people import People
from .person import Person
from .person_by_name import PersonByName
from .product import Product
from .product_by_name import ProductByName
from .products import Products
from .protocols import Protocols
from .update_episode_relations import UpdateEpisodeRelations
from .upsert_business_with_relations import UpsertBusinessWithRelations
from .upsert_product_with_relations import UpsertProductWithRelations


def gql(q: str) -> str:
    return q


class Client(AsyncBaseClient):
    async def login(self, email: str, password: str, **kwargs: Any) -> Login:
        query = gql(
            """
            mutation Login($email: String!, $password: String!) {
              login(email: $email, password: $password) {
                token
                user {
                  id
                  email
                  name
                  role
                }
              }
            }
            """
        )
        variables: dict[str, object] = {"email": email, "password": password}
        response = await self.execute(
            query=query, operation_name="Login", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return Login.model_validate(data)

    async def upsert_business_with_relations(
        self, input: BusinessUpsertRelationFieldsInput, **kwargs: Any
    ) -> UpsertBusinessWithRelations:
        query = gql(
            """
            mutation UpsertBusinessWithRelations($input: BusinessUpsertRelationFieldsInput!) {
              upsertBusinessWithRelations(input: $input) {
                id
                name
                description
                website
                mediaLinks {
                  url
                  description
                  posterUrl
                }
                products {
                  id
                  name
                  description
                  price
                  ingredients
                  sourceUrl
                  mediaLinks {
                    url
                    description
                    posterUrl
                  }
                  compounds {
                    id
                    name
                    description
                    aliases
                    mediaLinks {
                      url
                      description
                      posterUrl
                    }
                  }
                }
                owners {
                  id
                  name
                  role
                  bio
                  mediaLinks {
                    url
                    description
                    posterUrl
                  }
                }
                executives {
                  person {
                    id
                    name
                    role
                    bio
                    mediaLinks {
                      url
                      description
                      posterUrl
                    }
                  }
                  title
                  role
                }
              }
            }
            """
        )
        variables: dict[str, object] = {"input": input}
        response = await self.execute(
            query=query,
            operation_name="UpsertBusinessWithRelations",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return UpsertBusinessWithRelations.model_validate(data)

    async def upsert_product_with_relations(
        self, input: ProductUpsertRelationFieldsInput, **kwargs: Any
    ) -> UpsertProductWithRelations:
        query = gql(
            """
            mutation UpsertProductWithRelations($input: ProductUpsertRelationFieldsInput!) {
              upsertProductWithRelations(input: $input) {
                id
                name
                description
                price
                ingredients
                sourceUrl
                mediaLinks {
                  url
                  description
                  posterUrl
                }
                business {
                  id
                  name
                  description
                  website
                }
                compounds {
                  id
                  name
                  description
                  aliases
                  mediaLinks {
                    url
                    description
                    posterUrl
                  }
                }
              }
            }
            """
        )
        variables: dict[str, object] = {"input": input}
        response = await self.execute(
            query=query,
            operation_name="UpsertProductWithRelations",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return UpsertProductWithRelations.model_validate(data)

    async def update_episode_relations(
        self, input: EpisodeUpdateRelationFieldsInput, **kwargs: Any
    ) -> UpdateEpisodeRelations:
        query = gql(
            """
            mutation UpdateEpisodeRelations($input: EpisodeUpdateRelationFieldsInput!) {
              updateEpisodeRelations(input: $input) {
                id
                channelName
                episodeNumber
                episodeTitle
                episodePageUrl
                episodeTranscriptUrl
                publishedAt
                summaryShort
                webPageSummary
                summaryDetailed
                publishedSummary
                youtubeVideoId
                youtubeWatchUrl
                youtubeEmbedUrl
                takeaways
                s3TranscriptKey
                s3TranscriptUrl
                mediaLinks {
                  url
                  description
                  posterUrl
                }
                guests {
                  id
                  name
                  role
                  bio
                  mediaLinks {
                    url
                    description
                    posterUrl
                  }
                }
                sponsorBusinesses {
                  id
                  name
                  description
                  website
                  mediaLinks {
                    url
                    description
                    posterUrl
                  }
                }
                protocols {
                  id
                  name
                  description
                  categories
                  goals
                  steps
                  cautions
                  aliases
                  sourceUrl
                }
              }
            }
            """
        )
        variables: dict[str, object] = {"input": input}
        response = await self.execute(
            query=query,
            operation_name="UpdateEpisodeRelations",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return UpdateEpisodeRelations.model_validate(data)

    async def business(self, id: str, **kwargs: Any) -> Business:
        query = gql(
            """
            query Business($id: ID!) {
              business(id: $id) {
                id
                name
                description
                website
                mediaLinks {
                  url
                  description
                }
                products {
                  id
                  name
                  description
                }
                owners {
                  id
                  name
                  role
                }
                executives {
                  role
                  title
                  person {
                    id
                    name
                    role
                  }
                }
                sponsoredEpisodes {
                  id
                  episodeTitle
                  channelName
                }
              }
            }
            """
        )
        variables: dict[str, object] = {"id": id}
        response = await self.execute(
            query=query, operation_name="Business", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return Business.model_validate(data)

    async def businesses(
        self,
        limit: Union[Optional[int], UnsetType] = UNSET,
        offset: Union[Optional[int], UnsetType] = UNSET,
        **kwargs: Any
    ) -> Businesses:
        query = gql(
            """
            query Businesses($limit: Int, $offset: Int) {
              businesses(limit: $limit, offset: $offset) {
                id
                name
                description
                website
              }
            }
            """
        )
        variables: dict[str, object] = {"limit": limit, "offset": offset}
        response = await self.execute(
            query=query, operation_name="Businesses", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return Businesses.model_validate(data)

    async def product(self, id: str, **kwargs: Any) -> Product:
        query = gql(
            """
            query Product($id: ID!) {
              product(id: $id) {
                id
                name
                description
                ingredients
                sourceUrl
                mediaLinks {
                  url
                  description
                }
                business {
                  id
                  name
                  description
                }
                compounds {
                  id
                  name
                  description
                }
                sponsorEpisodes {
                  id
                  episodeTitle
                  channelName
                }
              }
            }
            """
        )
        variables: dict[str, object] = {"id": id}
        response = await self.execute(
            query=query, operation_name="Product", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return Product.model_validate(data)

    async def products(
        self,
        limit: Union[Optional[int], UnsetType] = UNSET,
        offset: Union[Optional[int], UnsetType] = UNSET,
        **kwargs: Any
    ) -> Products:
        query = gql(
            """
            query Products($limit: Int, $offset: Int) {
              products(limit: $limit, offset: $offset) {
                id
                name
                description
                ingredients
              }
            }
            """
        )
        variables: dict[str, object] = {"limit": limit, "offset": offset}
        response = await self.execute(
            query=query, operation_name="Products", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return Products.model_validate(data)

    async def person(self, id: str, **kwargs: Any) -> Person:
        query = gql(
            """
            query Person($id: ID!) {
              person(id: $id) {
                id
                name
                role
                bio
                mediaLinks {
                  url
                  description
                }
                businesses {
                  id
                  name
                  description
                }
                episodes {
                  id
                  episodeTitle
                  channelName
                }
              }
            }
            """
        )
        variables: dict[str, object] = {"id": id}
        response = await self.execute(
            query=query, operation_name="Person", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return Person.model_validate(data)

    async def people(
        self,
        limit: Union[Optional[int], UnsetType] = UNSET,
        offset: Union[Optional[int], UnsetType] = UNSET,
        **kwargs: Any
    ) -> People:
        query = gql(
            """
            query People($limit: Int, $offset: Int) {
              people(limit: $limit, offset: $offset) {
                id
                name
                role
              }
            }
            """
        )
        variables: dict[str, object] = {"limit": limit, "offset": offset}
        response = await self.execute(
            query=query, operation_name="People", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return People.model_validate(data)

    async def product_by_name(self, name: str, **kwargs: Any) -> ProductByName:
        query = gql(
            """
            query ProductByName($name: String!) {
              productByName(name: $name) {
                id
                name
                description
              }
            }
            """
        )
        variables: dict[str, object] = {"name": name}
        response = await self.execute(
            query=query, operation_name="ProductByName", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return ProductByName.model_validate(data)

    async def compound_by_name(self, name: str, **kwargs: Any) -> CompoundByName:
        query = gql(
            """
            query CompoundByName($name: String!) {
              compoundByName(name: $name) {
                id
                name
                description
              }
            }
            """
        )
        variables: dict[str, object] = {"name": name}
        response = await self.execute(
            query=query, operation_name="CompoundByName", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return CompoundByName.model_validate(data)

    async def person_by_name(self, name: str, **kwargs: Any) -> PersonByName:
        query = gql(
            """
            query PersonByName($name: String!) {
              personByName(name: $name) {
                id
                name
                role
              }
            }
            """
        )
        variables: dict[str, object] = {"name": name}
        response = await self.execute(
            query=query, operation_name="PersonByName", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return PersonByName.model_validate(data)

    async def business_by_name(self, name: str, **kwargs: Any) -> BusinessByName:
        query = gql(
            """
            query BusinessByName($name: String!) {
              businessByName(name: $name) {
                id
                name
                description
              }
            }
            """
        )
        variables: dict[str, object] = {"name": name}
        response = await self.execute(
            query=query, operation_name="BusinessByName", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return BusinessByName.model_validate(data)

    async def episode(self, id: str, **kwargs: Any) -> Episode:
        query = gql(
            """
            query Episode($id: ID!) {
              episode(id: $id) {
                id
                channelName
                episodeNumber
                episodeTitle
                episodeTranscriptUrl
                episodePageUrl
                webPageSummary
                takeaways
                s3TranscriptKey
                s3TranscriptUrl
                youtubeVideoId
                youtubeWatchUrl
                youtubeEmbedUrl
                mediaLinks {
                  url
                  description
                }
                publishedAt
                guests {
                  id
                  name
                  role
                }
                summaryDetailed
                publishedSummary
                businessLinks
                sponsorBusinesses {
                  id
                  name
                  description
                }
              }
            }
            """
        )
        variables: dict[str, object] = {"id": id}
        response = await self.execute(
            query=query, operation_name="Episode", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return Episode.model_validate(data)

    async def episode_by_page_url(
        self, page_url: str, **kwargs: Any
    ) -> EpisodeByPageUrl:
        query = gql(
            """
            query EpisodeByPageUrl($pageUrl: String!) {
              episodeByPageUrl(pageUrl: $pageUrl) {
                id
                episodeTitle
                channelName
                episodePageUrl
              }
            }
            """
        )
        variables: dict[str, object] = {"pageUrl": page_url}
        response = await self.execute(
            query=query,
            operation_name="EpisodeByPageUrl",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return EpisodeByPageUrl.model_validate(data)

    async def episodes(
        self,
        limit: Union[Optional[int], UnsetType] = UNSET,
        offset: Union[Optional[int], UnsetType] = UNSET,
        **kwargs: Any
    ) -> Episodes:
        query = gql(
            """
            query Episodes($limit: Int, $offset: Int) {
              episodes(limit: $limit, offset: $offset) {
                id
                episodeTitle
                channelName
                episodePageUrl
                episodeNumber
                publishedAt
              }
            }
            """
        )
        variables: dict[str, object] = {"limit": limit, "offset": offset}
        response = await self.execute(
            query=query, operation_name="Episodes", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return Episodes.model_validate(data)

    async def compound(self, id: str, **kwargs: Any) -> Compound:
        query = gql(
            """
            query Compound($id: ID!) {
              compound(id: $id) {
                id
                name
                description
                aliases
                mediaLinks {
                  url
                  description
                }
                products {
                  id
                  name
                  description
                }
                caseStudies {
                  id
                  title
                  summary
                }
              }
            }
            """
        )
        variables: dict[str, object] = {"id": id}
        response = await self.execute(
            query=query, operation_name="Compound", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return Compound.model_validate(data)

    async def compounds(
        self,
        limit: Union[Optional[int], UnsetType] = UNSET,
        offset: Union[Optional[int], UnsetType] = UNSET,
        **kwargs: Any
    ) -> Compounds:
        query = gql(
            """
            query Compounds($limit: Int, $offset: Int) {
              compounds(limit: $limit, offset: $offset) {
                id
                name
                description
                aliases
              }
            }
            """
        )
        variables: dict[str, object] = {"limit": limit, "offset": offset}
        response = await self.execute(
            query=query, operation_name="Compounds", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return Compounds.model_validate(data)

    async def protocols(
        self,
        limit: Union[Optional[int], UnsetType] = UNSET,
        offset: Union[Optional[int], UnsetType] = UNSET,
        **kwargs: Any
    ) -> Protocols:
        query = gql(
            """
            query Protocols($limit: Int, $offset: Int) {
              protocols(limit: $limit, offset: $offset) {
                id
                name
                description
                categories
                goals
              }
            }
            """
        )
        variables: dict[str, object] = {"limit": limit, "offset": offset}
        response = await self.execute(
            query=query, operation_name="Protocols", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return Protocols.model_validate(data)

    async def case_study(self, id: str, **kwargs: Any) -> CaseStudy:
        query = gql(
            """
            query CaseStudy($id: ID!) {
              caseStudy(id: $id) {
                id
                title
                summary
                url
                sourceType
                mediaLinks {
                  url
                  description
                }
                episodes {
                  id
                  episodeTitle
                  channelName
                }
                compounds {
                  id
                  name
                  description
                }
                products {
                  id
                  name
                  description
                }
                protocols {
                  id
                  name
                  description
                }
              }
            }
            """
        )
        variables: dict[str, object] = {"id": id}
        response = await self.execute(
            query=query, operation_name="CaseStudy", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return CaseStudy.model_validate(data)

    async def case_studies(
        self,
        limit: Union[Optional[int], UnsetType] = UNSET,
        offset: Union[Optional[int], UnsetType] = UNSET,
        **kwargs: Any
    ) -> CaseStudies:
        query = gql(
            """
            query CaseStudies($limit: Int, $offset: Int) {
              caseStudies(limit: $limit, offset: $offset) {
                id
                title
                summary
                url
              }
            }
            """
        )
        variables: dict[str, object] = {"limit": limit, "offset": offset}
        response = await self.execute(
            query=query, operation_name="CaseStudies", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return CaseStudies.model_validate(data)
