# Generated by ariadne-codegen
# Source: src/graphql/operations

from typing import Optional

from .base_model import BaseModel


class Compound(BaseModel):
    compound: Optional["CompoundCompound"]


class CompoundCompound(BaseModel):
    id: str
    name: str
    description: Optional[str]


Compound.model_rebuild()
