# Generated by ariadne-codegen
# Source: src/graphql/operations

from typing import List, Optional

from .base_model import BaseModel


class Compounds(BaseModel):
    compounds: List["CompoundsCompounds"]


class CompoundsCompounds(BaseModel):
    id: str
    name: str
    description: Optional[str]


Compounds.model_rebuild()
