# Generated by ariadne-codegen
# Source: src/graphql/operations

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class CompoundByName(BaseModel):
    compound_by_name: Optional["CompoundByNameCompoundByName"] = Field(
        alias="compoundByName"
    )


class CompoundByNameCompoundByName(BaseModel):
    id: str
    name: str
    description: Optional[str]


CompoundByName.model_rebuild()
