# Generated by ariadne-codegen
# Source: src/graphql/operations

from pydantic import Field

from .base_model import BaseModel


class CreateOrganization(BaseModel):
    create_organization: "CreateOrganizationCreateOrganization" = Field(
        alias="createOrganization"
    )


class CreateOrganizationCreateOrganization(BaseModel):
    organization_id: str = Field(alias="organizationId")
    name: str


CreateOrganization.model_rebuild()
