# Generated by ariadne-codegen
# Source: src/graphql/operations

from pydantic import Field

from .base_model import BaseModel


class CreateCaseStudy(BaseModel):
    create_case_study: "CreateCaseStudyCreateCaseStudy" = Field(alias="createCaseStudy")


class CreateCaseStudyCreateCaseStudy(BaseModel):
    id: str
    title: str
    summary: str


CreateCaseStudy.model_rebuild()
