# Generated by ariadne-codegen
# Source: src/graphql/operations

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class CreateBusiness(BaseModel):
    create_business: "CreateBusinessCreateBusiness" = Field(alias="createBusiness")


class CreateBusinessCreateBusiness(BaseModel):
    id: str
    name: str
    description: Optional[str]


CreateBusiness.model_rebuild()
