# Generated by ariadne-codegen
# Source: src/graphql/schema.graphql

from enum import Enum


class UserProvider(str, Enum):
    LOCAL = "LOCAL"
    GOOGLE = "GOOGLE"
    GITHUB = "GITHUB"
    APPLE = "APPLE"


class UserRole(str, Enum):
    ADMIN = "ADMIN"
    USER = "USER"


class CaseStudySourceType(str, Enum):
    PUBMED = "PUBMED"
    CLINICAL_TRIAL = "CLINICAL_TRIAL"
    ARTICLE = "ARTICLE"
    OTHER = "OTHER"
