# Generated by ariadne-codegen
# Source: src/graphql/operations

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class EpisodeByPageUrl(BaseModel):
    episode_by_page_url: Optional["EpisodeByPageUrlEpisodeByPageUrl"] = Field(
        alias="episodeByPageUrl"
    )


class EpisodeByPageUrlEpisodeByPageUrl(BaseModel):
    id: str
    episode_title: Optional[str] = Field(alias="episodeTitle")
    channel_name: str = Field(alias="channelName")
    episode_page_url: Optional[str] = Field(alias="episodePageUrl")


EpisodeByPageUrl.model_rebuild()
