# Generated by ariadne-codegen
# Source: src/graphql/operations

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel


class Episodes(BaseModel):
    episodes: List["EpisodesEpisodes"]


class EpisodesEpisodes(BaseModel):
    id: str
    episode_title: Optional[str] = Field(alias="episodeTitle")
    channel_name: str = Field(alias="channelName")


Episodes.model_rebuild()
