# Generated by ariadne-codegen
# Source: src/graphql/operations

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class Episode(BaseModel):
    episode: Optional["EpisodeEpisode"]


class EpisodeEpisode(BaseModel):
    id: str
    episode_title: Optional[str] = Field(alias="episodeTitle")
    channel_name: str = Field(alias="channelName")


Episode.model_rebuild()
