# Generated by ariadne-codegen
# Source: src/graphql/operations

from typing import Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import OrgType


class GetOrganizations(BaseModel):
    organizations: list["GetOrganizationsOrganizations"]


class GetOrganizationsOrganizations(BaseModel):
    organization_id: str = Field(alias="organizationId")
    name: str
    aliases: Optional[list[str]]
    org_type: OrgType = Field(alias="orgType")


GetOrganizations.model_rebuild()
