# Generated by ariadne-codegen
# Source: src/graphql/schema.graphql

from typing import Any, List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import CaseStudySourceType, UserProvider, UserRole


class MediaLinkInput(BaseModel):
    label: Optional[str] = None
    url: str
    type: Optional[str] = None


class UserUpsertInput(BaseModel):
    email: str
    password: Optional[str] = None
    provider: Optional[UserProvider] = None
    provider_id: Optional[str] = Field(alias="providerId", default=None)
    name: Optional[str] = None
    role: Optional[UserRole] = None
    media_links: Optional[List["MediaLinkInput"]] = Field(
        alias="mediaLinks", default=None
    )


class UserCreateInput(BaseModel):
    email: str
    password: Optional[str] = None
    provider: Optional[UserProvider] = None
    provider_id: Optional[str] = Field(alias="providerId", default=None)
    name: Optional[str] = None
    role: Optional[UserRole] = None
    media_links: Optional[List["MediaLinkInput"]] = Field(
        alias="mediaLinks", default=None
    )


class BusinessCreateWithIdsInput(BaseModel):
    name: str
    description: Optional[str] = None
    website: Optional[str] = None
    media_links: Optional[List["MediaLinkInput"]] = Field(
        alias="mediaLinks", default=None
    )
    owner_ids: Optional[List[str]] = Field(alias="ownerIds", default=None)
    product_ids: Optional[List[str]] = Field(alias="productIds", default=None)
    sponsor_episode_ids: Optional[List[str]] = Field(
        alias="sponsorEpisodeIds", default=None
    )


class BusinessUpdateWithIdsInput(BaseModel):
    id: str
    name: Optional[str] = None
    description: Optional[str] = None
    website: Optional[str] = None
    media_links: Optional[List["MediaLinkInput"]] = Field(
        alias="mediaLinks", default=None
    )
    owner_ids: Optional[List[str]] = Field(alias="ownerIds", default=None)
    product_ids: Optional[List[str]] = Field(alias="productIds", default=None)
    sponsor_episode_ids: Optional[List[str]] = Field(
        alias="sponsorEpisodeIds", default=None
    )


class BusinessOwnerNestedInput(BaseModel):
    id: Optional[str] = None
    name: Optional[str] = None
    role: Optional[str] = None
    bio: Optional[str] = None
    media_links: Optional[List["MediaLinkInput"]] = Field(
        alias="mediaLinks", default=None
    )


class BusinessProductNestedInput(BaseModel):
    id: Optional[str] = None
    name: Optional[str] = None
    description: Optional[str] = None
    ingredients: Optional[List[str]] = None
    media_links: Optional[List["MediaLinkInput"]] = Field(
        alias="mediaLinks", default=None
    )
    source_url: Optional[str] = Field(alias="sourceUrl", default=None)


class BusinessExecutiveRelationInput(BaseModel):
    person_id: str = Field(alias="personId")
    title: Optional[str] = None
    role: Optional[str] = None


class SponsorLinkObjectInput(BaseModel):
    text: Optional[str] = None
    links: Optional[List[str]] = None
    has_code_dave: Optional[bool] = Field(alias="hasCodeDave", default=None)
    code: Optional[str] = None
    brand: Optional[str] = None
    discount_percent: Optional[float] = Field(alias="discountPercent", default=None)


class WebPageTimelineInput(BaseModel):
    from_: str = Field(alias="from")
    to: str
    title: Optional[str] = None
    description: Optional[str] = None


class BusinessEpisodeNestedInput(BaseModel):
    id: Optional[str] = None
    channel_name: str = Field(alias="channelName")
    episode_number: Optional[int] = Field(alias="episodeNumber", default=None)
    episode_title: Optional[str] = Field(alias="episodeTitle", default=None)
    published_at: Optional[Any] = Field(alias="publishedAt", default=None)
    summary_short: Optional[str] = Field(alias="summaryShort", default=None)
    web_page_summary: Optional[str] = Field(alias="webPageSummary", default=None)
    summary_detailed: Optional[str] = Field(alias="summaryDetailed", default=None)
    youtube_video_id: Optional[str] = Field(alias="youtubeVideoId", default=None)
    youtube_watch_url: Optional[str] = Field(alias="youtubeWatchUrl", default=None)
    youtube_embed_url: Optional[str] = Field(alias="youtubeEmbedUrl", default=None)
    takeaways: Optional[List[str]] = None
    s_3_transcript_key: Optional[str] = Field(alias="s3TranscriptKey", default=None)
    s_3_transcript_url: Optional[str] = Field(alias="s3TranscriptUrl", default=None)
    media_links: Optional[List["MediaLinkInput"]] = Field(
        alias="mediaLinks", default=None
    )
    sponsor_link_objects: Optional[List["SponsorLinkObjectInput"]] = Field(
        alias="sponsorLinkObjects", default=None
    )
    web_page_timelines: Optional[List["WebPageTimelineInput"]] = Field(
        alias="webPageTimelines", default=None
    )


class BusinessUpdateRelationFieldsInput(BaseModel):
    id: str
    owner_ids: Optional[List[str]] = Field(alias="ownerIds", default=None)
    owners_nested: Optional[List["BusinessOwnerNestedInput"]] = Field(
        alias="ownersNested", default=None
    )
    product_ids: Optional[List[str]] = Field(alias="productIds", default=None)
    products_nested: Optional[List["BusinessProductNestedInput"]] = Field(
        alias="productsNested", default=None
    )
    executives: Optional[List["BusinessExecutiveRelationInput"]] = None
    sponsor_episode_ids: Optional[List[str]] = Field(
        alias="sponsorEpisodeIds", default=None
    )
    sponsor_episodes_nested: Optional[List["BusinessEpisodeNestedInput"]] = Field(
        alias="sponsorEpisodesNested", default=None
    )


class ProductCreateWithIdsInput(BaseModel):
    name: str
    business_id: str = Field(alias="businessId")
    description: Optional[str] = None
    ingredients: Optional[List[str]] = None
    media_links: Optional[List["MediaLinkInput"]] = Field(
        alias="mediaLinks", default=None
    )
    source_url: Optional[str] = Field(alias="sourceUrl", default=None)
    compound_ids: Optional[List[str]] = Field(alias="compoundIds", default=None)


class ProductUpdateWithIdsInput(BaseModel):
    id: str
    name: Optional[str] = None
    description: Optional[str] = None
    ingredients: Optional[List[str]] = None
    media_links: Optional[List["MediaLinkInput"]] = Field(
        alias="mediaLinks", default=None
    )
    source_url: Optional[str] = Field(alias="sourceUrl", default=None)
    compound_ids: Optional[List[str]] = Field(alias="compoundIds", default=None)


class ProductCompoundNestedInput(BaseModel):
    id: Optional[str] = None
    name: Optional[str] = None
    description: Optional[str] = None
    aliases: Optional[List[str]] = None
    media_links: Optional[List["MediaLinkInput"]] = Field(
        alias="mediaLinks", default=None
    )


class ProductUpdateRelationFieldsInput(BaseModel):
    id: str
    compound_ids: Optional[List[str]] = Field(alias="compoundIds", default=None)
    compounds_nested: Optional[List["ProductCompoundNestedInput"]] = Field(
        alias="compoundsNested", default=None
    )


class PersonCreateWithIdsInput(BaseModel):
    name: str
    role: Optional[str] = None
    bio: Optional[str] = None
    media_links: Optional[List["MediaLinkInput"]] = Field(
        alias="mediaLinks", default=None
    )
    business_ids: Optional[List[str]] = Field(alias="businessIds", default=None)


class PersonUpdateWithIdsInput(BaseModel):
    id: str
    name: Optional[str] = None
    role: Optional[str] = None
    bio: Optional[str] = None
    media_links: Optional[List["MediaLinkInput"]] = Field(
        alias="mediaLinks", default=None
    )
    business_ids: Optional[List[str]] = Field(alias="businessIds", default=None)


class PersonBusinessNestedInput(BaseModel):
    id: Optional[str] = None
    name: Optional[str] = None
    description: Optional[str] = None
    website: Optional[str] = None
    media_links: Optional[List["MediaLinkInput"]] = Field(
        alias="mediaLinks", default=None
    )


class PersonUpdateRelationFieldsInput(BaseModel):
    id: str
    business_ids: Optional[List[str]] = Field(alias="businessIds", default=None)
    businesses_nested: Optional[List["PersonBusinessNestedInput"]] = Field(
        alias="businessesNested", default=None
    )


class EpisodeCreateWithIdsInput(BaseModel):
    channel_name: str = Field(alias="channelName")
    episode_number: Optional[int] = Field(alias="episodeNumber", default=None)
    episode_title: Optional[str] = Field(alias="episodeTitle", default=None)
    episode_page_url: Optional[str] = Field(alias="episodePageUrl", default=None)
    episode_transcript_url: Optional[str] = Field(
        alias="episodeTranscriptUrl", default=None
    )
    published_at: Optional[Any] = Field(alias="publishedAt", default=None)
    summary_short: Optional[str] = Field(alias="summaryShort", default=None)
    web_page_summary: Optional[str] = Field(alias="webPageSummary", default=None)
    summary_detailed: Optional[str] = Field(alias="summaryDetailed", default=None)
    youtube_video_id: Optional[str] = Field(alias="youtubeVideoId", default=None)
    youtube_watch_url: Optional[str] = Field(alias="youtubeWatchUrl", default=None)
    youtube_embed_url: Optional[str] = Field(alias="youtubeEmbedUrl", default=None)
    takeaways: Optional[List[str]] = None
    s_3_transcript_key: Optional[str] = Field(alias="s3TranscriptKey", default=None)
    s_3_transcript_url: Optional[str] = Field(alias="s3TranscriptUrl", default=None)
    media_links: Optional[List["MediaLinkInput"]] = Field(
        alias="mediaLinks", default=None
    )
    sponsor_link_objects: Optional[List["SponsorLinkObjectInput"]] = Field(
        alias="sponsorLinkObjects", default=None
    )
    web_page_timelines: Optional[List["WebPageTimelineInput"]] = Field(
        alias="webPageTimelines", default=None
    )
    guest_ids: Optional[List[str]] = Field(alias="guestIds", default=None)
    sponsor_business_ids: Optional[List[str]] = Field(
        alias="sponsorBusinessIds", default=None
    )


class EpisodeUpdateWithIdsInput(BaseModel):
    id: str
    channel_name: Optional[str] = Field(alias="channelName", default=None)
    episode_number: Optional[int] = Field(alias="episodeNumber", default=None)
    episode_title: Optional[str] = Field(alias="episodeTitle", default=None)
    episode_page_url: Optional[str] = Field(alias="episodePageUrl", default=None)
    episode_transcript_url: Optional[str] = Field(
        alias="episodeTranscriptUrl", default=None
    )
    published_at: Optional[Any] = Field(alias="publishedAt", default=None)
    summary_short: Optional[str] = Field(alias="summaryShort", default=None)
    web_page_summary: Optional[str] = Field(alias="webPageSummary", default=None)
    summary_detailed: Optional[str] = Field(alias="summaryDetailed", default=None)
    youtube_video_id: Optional[str] = Field(alias="youtubeVideoId", default=None)
    youtube_watch_url: Optional[str] = Field(alias="youtubeWatchUrl", default=None)
    youtube_embed_url: Optional[str] = Field(alias="youtubeEmbedUrl", default=None)
    takeaways: Optional[List[str]] = None
    s_3_transcript_key: Optional[str] = Field(alias="s3TranscriptKey", default=None)
    s_3_transcript_url: Optional[str] = Field(alias="s3TranscriptUrl", default=None)
    media_links: Optional[List["MediaLinkInput"]] = Field(
        alias="mediaLinks", default=None
    )
    sponsor_link_objects: Optional[List["SponsorLinkObjectInput"]] = Field(
        alias="sponsorLinkObjects", default=None
    )
    web_page_timelines: Optional[List["WebPageTimelineInput"]] = Field(
        alias="webPageTimelines", default=None
    )
    guest_ids: Optional[List[str]] = Field(alias="guestIds", default=None)
    sponsor_business_ids: Optional[List[str]] = Field(
        alias="sponsorBusinessIds", default=None
    )


class EpisodeGuestNestedInput(BaseModel):
    id: Optional[str] = None
    name: Optional[str] = None
    role: Optional[str] = None
    bio: Optional[str] = None
    media_links: Optional[List["MediaLinkInput"]] = Field(
        alias="mediaLinks", default=None
    )


class EpisodeSponsorBusinessNestedInput(BaseModel):
    id: Optional[str] = None
    name: Optional[str] = None
    description: Optional[str] = None
    website: Optional[str] = None
    media_links: Optional[List["MediaLinkInput"]] = Field(
        alias="mediaLinks", default=None
    )


class EpisodeUpdateRelationFieldsInput(BaseModel):
    id: str
    guest_ids: Optional[List[str]] = Field(alias="guestIds", default=None)
    guests_nested: Optional[List["EpisodeGuestNestedInput"]] = Field(
        alias="guestsNested", default=None
    )
    sponsor_business_ids: Optional[List[str]] = Field(
        alias="sponsorBusinessIds", default=None
    )
    sponsor_businesses_nested: Optional[List["EpisodeSponsorBusinessNestedInput"]] = (
        Field(alias="sponsorBusinessesNested", default=None)
    )


class CompoundCreateWithIdsInput(BaseModel):
    name: str
    description: Optional[str] = None
    aliases: Optional[List[str]] = None
    media_links: Optional[List["MediaLinkInput"]] = Field(
        alias="mediaLinks", default=None
    )
    product_ids: Optional[List[str]] = Field(alias="productIds", default=None)


class CompoundUpdateWithIdsInput(BaseModel):
    id: str
    name: Optional[str] = None
    description: Optional[str] = None
    aliases: Optional[List[str]] = None
    media_links: Optional[List["MediaLinkInput"]] = Field(
        alias="mediaLinks", default=None
    )
    product_ids: Optional[List[str]] = Field(alias="productIds", default=None)


class CompoundProductNestedInput(BaseModel):
    id: Optional[str] = None
    name: Optional[str] = None
    description: Optional[str] = None
    ingredients: Optional[List[str]] = None
    media_links: Optional[List["MediaLinkInput"]] = Field(
        alias="mediaLinks", default=None
    )
    source_url: Optional[str] = Field(alias="sourceUrl", default=None)


class CompoundUpdateRelationFieldsInput(BaseModel):
    id: str
    product_ids: Optional[List[str]] = Field(alias="productIds", default=None)
    products_nested: Optional[List["CompoundProductNestedInput"]] = Field(
        alias="productsNested", default=None
    )


class CaseStudyCreateWithOptionalIdsInput(BaseModel):
    title: str
    summary: str
    url: Optional[str] = None
    source_type: Optional[CaseStudySourceType] = Field(alias="sourceType", default=None)
    episode_ids: Optional[List[str]] = Field(alias="episodeIds", default=None)
    compound_ids: Optional[List[str]] = Field(alias="compoundIds", default=None)


class CaseStudyUpdateWithOptionalIdsInput(BaseModel):
    id: str
    title: Optional[str] = None
    summary: Optional[str] = None
    url: Optional[str] = None
    source_type: Optional[CaseStudySourceType] = Field(alias="sourceType", default=None)
    episode_ids: Optional[List[str]] = Field(alias="episodeIds", default=None)
    compound_ids: Optional[List[str]] = Field(alias="compoundIds", default=None)


class UserMassSaveInput(BaseModel):
    user_id: str = Field(alias="userId")
    episode_ids: Optional[List[str]] = Field(alias="episodeIds", default=None)
    product_ids: Optional[List[str]] = Field(alias="productIds", default=None)
    business_ids: Optional[List[str]] = Field(alias="businessIds", default=None)


UserUpsertInput.model_rebuild()
UserCreateInput.model_rebuild()
BusinessCreateWithIdsInput.model_rebuild()
BusinessUpdateWithIdsInput.model_rebuild()
BusinessOwnerNestedInput.model_rebuild()
BusinessProductNestedInput.model_rebuild()
BusinessEpisodeNestedInput.model_rebuild()
BusinessUpdateRelationFieldsInput.model_rebuild()
ProductCreateWithIdsInput.model_rebuild()
ProductUpdateWithIdsInput.model_rebuild()
ProductCompoundNestedInput.model_rebuild()
ProductUpdateRelationFieldsInput.model_rebuild()
PersonCreateWithIdsInput.model_rebuild()
PersonUpdateWithIdsInput.model_rebuild()
PersonBusinessNestedInput.model_rebuild()
PersonUpdateRelationFieldsInput.model_rebuild()
EpisodeCreateWithIdsInput.model_rebuild()
EpisodeUpdateWithIdsInput.model_rebuild()
EpisodeGuestNestedInput.model_rebuild()
EpisodeSponsorBusinessNestedInput.model_rebuild()
EpisodeUpdateRelationFieldsInput.model_rebuild()
CompoundCreateWithIdsInput.model_rebuild()
CompoundUpdateWithIdsInput.model_rebuild()
CompoundProductNestedInput.model_rebuild()
CompoundUpdateRelationFieldsInput.model_rebuild()
