# Generated by ariadne-codegen
# Source: src/graphql/operations

from typing import Any, Optional

from pydantic import Field

from .base_model import BaseModel


class LinkResearchRunUsesPlan(BaseModel):
    link_research_run_uses_plan: "LinkResearchRunUsesPlanLinkResearchRunUsesPlan" = (
        Field(alias="linkResearchRunUsesPlan")
    )


class LinkResearchRunUsesPlanLinkResearchRunUsesPlan(BaseModel):
    research_run_ref_id: str = Field(alias="researchRunRefId")
    mongo_run_id: str = Field(alias="mongoRunId")
    label: Optional[str]
    started_at: Any = Field(alias="startedAt")
    ended_at: Any = Field(alias="endedAt")
    valid_at: Optional[Any] = Field(alias="validAt")
    invalid_at: Optional[Any] = Field(alias="invalidAt")
    expired_at: Optional[Any] = Field(alias="expiredAt")
    created_at: Any = Field(alias="createdAt")
    updated_at: Any = Field(alias="updatedAt")
    uses_plan: Optional[
        list["LinkResearchRunUsesPlanLinkResearchRunUsesPlanUsesPlan"]
    ] = Field(alias="usesPlan")


class LinkResearchRunUsesPlanLinkResearchRunUsesPlanUsesPlan(BaseModel):
    research_plan_ref: (
        "LinkResearchRunUsesPlanLinkResearchRunUsesPlanUsesPlanResearchPlanRef"
    ) = Field(alias="researchPlanRef")
    valid_at: Optional[Any] = Field(alias="validAt")
    invalid_at: Optional[Any] = Field(alias="invalidAt")
    expired_at: Optional[Any] = Field(alias="expiredAt")
    created_at: Any = Field(alias="createdAt")


class LinkResearchRunUsesPlanLinkResearchRunUsesPlanUsesPlanResearchPlanRef(BaseModel):
    research_plan_ref_id: str = Field(alias="researchPlanRefId")
    mongo_plan_id: str = Field(alias="mongoPlanId")
    label: Optional[str]
    version: Optional[str]
    valid_at: Optional[Any] = Field(alias="validAt")
    invalid_at: Optional[Any] = Field(alias="invalidAt")
    expired_at: Optional[Any] = Field(alias="expiredAt")
    created_at: Any = Field(alias="createdAt")
    updated_at: Any = Field(alias="updatedAt")


LinkResearchRunUsesPlan.model_rebuild()
LinkResearchRunUsesPlanLinkResearchRunUsesPlan.model_rebuild()
LinkResearchRunUsesPlanLinkResearchRunUsesPlanUsesPlan.model_rebuild()
