# Generated by ariadne-codegen
# Source: src/graphql/operations

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class PersonByName(BaseModel):
    person_by_name: Optional["PersonByNamePersonByName"] = Field(alias="personByName")


class PersonByNamePersonByName(BaseModel):
    id: str
    name: str
    role: Optional[str]


PersonByName.model_rebuild()
