# Generated by ariadne-codegen
# Source: src/graphql/operations

from typing import Optional

from .base_model import BaseModel


class Person(BaseModel):
    person: Optional["PersonPerson"]


class PersonPerson(BaseModel):
    id: str
    name: str
    role: Optional[str]


Person.model_rebuild()
