# Generated by ariadne-codegen
# Source: src/graphql/operations

from typing import Optional

from .base_model import BaseModel


class Product(BaseModel):
    product: Optional["ProductProduct"]


class ProductProduct(BaseModel):
    id: str
    name: str
    description: Optional[str]


Product.model_rebuild()
