# Generated by ariadne-codegen
# Source: src/graphql/operations

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class ProductByName(BaseModel):
    product_by_name: Optional["ProductByNameProductByName"] = Field(
        alias="productByName"
    )


class ProductByNameProductByName(BaseModel):
    id: str
    name: str
    description: Optional[str]


ProductByName.model_rebuild()
