# Generated by ariadne-codegen
# Source: src/graphql/operations

from typing import List, Optional

from .base_model import BaseModel


class Products(BaseModel):
    products: List["ProductsProducts"]


class ProductsProducts(BaseModel):
    id: str
    name: str
    description: Optional[str]


Products.model_rebuild()
