# Generated by ariadne-codegen
# Source: src/graphql/operations

from typing import Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import SearchReasonKind


class SearchOrganizations(BaseModel):
    search_organizations: "SearchOrganizationsSearchOrganizations" = Field(
        alias="searchOrganizations"
    )


class SearchOrganizationsSearchOrganizations(BaseModel):
    items: list["SearchOrganizationsSearchOrganizationsItems"]
    page_info: "SearchOrganizationsSearchOrganizationsPageInfo" = Field(
        alias="pageInfo"
    )


class SearchOrganizationsSearchOrganizationsItems(BaseModel):
    node: "SearchOrganizationsSearchOrganizationsItemsNode"
    score: Optional[float]
    reasons: Optional[list["SearchOrganizationsSearchOrganizationsItemsReasons"]]


class SearchOrganizationsSearchOrganizationsItemsNode(BaseModel):
    organization_id: str = Field(alias="organizationId")
    name: str


class SearchOrganizationsSearchOrganizationsItemsReasons(BaseModel):
    kind: SearchReasonKind
    field: Optional[str]
    value: Optional[str]
    score: Optional[float]
    detail: Optional[str]


class SearchOrganizationsSearchOrganizationsPageInfo(BaseModel):
    has_next_page: bool = Field(alias="hasNextPage")
    end_cursor: Optional[str] = Field(alias="endCursor")


SearchOrganizations.model_rebuild()
SearchOrganizationsSearchOrganizations.model_rebuild()
SearchOrganizationsSearchOrganizationsItems.model_rebuild()
