# Generated by ariadne-codegen
# Source: src/graphql/operations

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class UpdatePersonRelations(BaseModel):
    update_person_relations: Optional["UpdatePersonRelationsUpdatePersonRelations"] = (
        Field(alias="updatePersonRelations")
    )


class UpdatePersonRelationsUpdatePersonRelations(BaseModel):
    id: str
    name: str


UpdatePersonRelations.model_rebuild()
