# Generated by ariadne-codegen
# Source: src/graphql/operations

from typing import Any, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import ProtocolCategory


class UpdateEpisodeRelations(BaseModel):
    update_episode_relations: Optional[
        "UpdateEpisodeRelationsUpdateEpisodeRelations"
    ] = Field(alias="updateEpisodeRelations")


class UpdateEpisodeRelationsUpdateEpisodeRelations(BaseModel):
    id: str
    channel_name: str = Field(alias="channelName")
    episode_number: Optional[int] = Field(alias="episodeNumber")
    episode_title: Optional[str] = Field(alias="episodeTitle")
    episode_page_url: Optional[str] = Field(alias="episodePageUrl")
    episode_transcript_url: Optional[str] = Field(alias="episodeTranscriptUrl")
    published_at: Optional[Any] = Field(alias="publishedAt")
    summary_short: Optional[str] = Field(alias="summaryShort")
    web_page_summary: Optional[str] = Field(alias="webPageSummary")
    summary_detailed: Optional[str] = Field(alias="summaryDetailed")
    published_summary: Optional[str] = Field(alias="publishedSummary")
    youtube_video_id: Optional[str] = Field(alias="youtubeVideoId")
    youtube_watch_url: Optional[str] = Field(alias="youtubeWatchUrl")
    youtube_embed_url: Optional[str] = Field(alias="youtubeEmbedUrl")
    takeaways: list[str]
    s_3_transcript_key: Optional[str] = Field(alias="s3TranscriptKey")
    s_3_transcript_url: Optional[str] = Field(alias="s3TranscriptUrl")
    media_links: Optional[
        list["UpdateEpisodeRelationsUpdateEpisodeRelationsMediaLinks"]
    ] = Field(alias="mediaLinks")
    guests: Optional[list["UpdateEpisodeRelationsUpdateEpisodeRelationsGuests"]]
    sponsor_businesses: Optional[
        list["UpdateEpisodeRelationsUpdateEpisodeRelationsSponsorBusinesses"]
    ] = Field(alias="sponsorBusinesses")
    protocols: Optional[list["UpdateEpisodeRelationsUpdateEpisodeRelationsProtocols"]]


class UpdateEpisodeRelationsUpdateEpisodeRelationsMediaLinks(BaseModel):
    url: str
    description: Optional[str]
    poster_url: Optional[str] = Field(alias="posterUrl")


class UpdateEpisodeRelationsUpdateEpisodeRelationsGuests(BaseModel):
    id: str
    name: str
    role: Optional[str]
    bio: Optional[str]
    media_links: Optional[
        list["UpdateEpisodeRelationsUpdateEpisodeRelationsGuestsMediaLinks"]
    ] = Field(alias="mediaLinks")


class UpdateEpisodeRelationsUpdateEpisodeRelationsGuestsMediaLinks(BaseModel):
    url: str
    description: Optional[str]
    poster_url: Optional[str] = Field(alias="posterUrl")


class UpdateEpisodeRelationsUpdateEpisodeRelationsSponsorBusinesses(BaseModel):
    id: str
    name: str
    description: Optional[str]
    website: Optional[str]
    media_links: Optional[
        list["UpdateEpisodeRelationsUpdateEpisodeRelationsSponsorBusinessesMediaLinks"]
    ] = Field(alias="mediaLinks")


class UpdateEpisodeRelationsUpdateEpisodeRelationsSponsorBusinessesMediaLinks(
    BaseModel
):
    url: str
    description: Optional[str]
    poster_url: Optional[str] = Field(alias="posterUrl")


class UpdateEpisodeRelationsUpdateEpisodeRelationsProtocols(BaseModel):
    id: str
    name: str
    description: Optional[str]
    categories: list[ProtocolCategory]
    goals: list[str]
    steps: list[str]
    cautions: list[str]
    aliases: list[str]
    source_url: Optional[str] = Field(alias="sourceUrl")


UpdateEpisodeRelations.model_rebuild()
UpdateEpisodeRelationsUpdateEpisodeRelations.model_rebuild()
UpdateEpisodeRelationsUpdateEpisodeRelationsGuests.model_rebuild()
UpdateEpisodeRelationsUpdateEpisodeRelationsSponsorBusinesses.model_rebuild()
