# Generated by ariadne-codegen
# Source: src/graphql/operations

from typing import Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import OrgType


class UpdateOrganization(BaseModel):
    update_organization: "UpdateOrganizationUpdateOrganization" = Field(
        alias="updateOrganization"
    )


class UpdateOrganizationUpdateOrganization(BaseModel):
    organization_id: str = Field(alias="organizationId")
    name: str
    aliases: Optional[list[str]]
    org_type: OrgType = Field(alias="orgType")


UpdateOrganization.model_rebuild()
