# Generated by ariadne-codegen
# Source: src/graphql/operations

from pydantic import Field

from .base_model import BaseModel


class UpdateCaseStudy(BaseModel):
    update_case_study: "UpdateCaseStudyUpdateCaseStudy" = Field(alias="updateCaseStudy")


class UpdateCaseStudyUpdateCaseStudy(BaseModel):
    id: str
    title: str
    summary: str


UpdateCaseStudy.model_rebuild()
