# Generated by ariadne-codegen
# Source: src/graphql/operations

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class UpsertBusinessWithRelations(BaseModel):
    upsert_business_with_relations: Optional[
        "UpsertBusinessWithRelationsUpsertBusinessWithRelations"
    ] = Field(alias="upsertBusinessWithRelations")


class UpsertBusinessWithRelationsUpsertBusinessWithRelations(BaseModel):
    id: str
    name: str
    description: Optional[str]
    website: Optional[str]
    media_links: Optional[
        list["UpsertBusinessWithRelationsUpsertBusinessWithRelationsMediaLinks"]
    ] = Field(alias="mediaLinks")
    products: Optional[
        list["UpsertBusinessWithRelationsUpsertBusinessWithRelationsProducts"]
    ]
    owners: Optional[
        list["UpsertBusinessWithRelationsUpsertBusinessWithRelationsOwners"]
    ]
    executives: Optional[
        list["UpsertBusinessWithRelationsUpsertBusinessWithRelationsExecutives"]
    ]


class UpsertBusinessWithRelationsUpsertBusinessWithRelationsMediaLinks(BaseModel):
    url: str
    description: Optional[str]
    poster_url: Optional[str] = Field(alias="posterUrl")


class UpsertBusinessWithRelationsUpsertBusinessWithRelationsProducts(BaseModel):
    id: str
    name: str
    description: Optional[str]
    price: Optional[float]
    ingredients: list[str]
    source_url: Optional[str] = Field(alias="sourceUrl")
    media_links: Optional[
        list["UpsertBusinessWithRelationsUpsertBusinessWithRelationsProductsMediaLinks"]
    ] = Field(alias="mediaLinks")
    compounds: Optional[
        list["UpsertBusinessWithRelationsUpsertBusinessWithRelationsProductsCompounds"]
    ]


class UpsertBusinessWithRelationsUpsertBusinessWithRelationsProductsMediaLinks(
    BaseModel
):
    url: str
    description: Optional[str]
    poster_url: Optional[str] = Field(alias="posterUrl")


class UpsertBusinessWithRelationsUpsertBusinessWithRelationsProductsCompounds(
    BaseModel
):
    id: str
    name: str
    description: Optional[str]
    aliases: list[str]
    media_links: Optional[
        list[
            "UpsertBusinessWithRelationsUpsertBusinessWithRelationsProductsCompoundsMediaLinks"
        ]
    ] = Field(alias="mediaLinks")


class UpsertBusinessWithRelationsUpsertBusinessWithRelationsProductsCompoundsMediaLinks(
    BaseModel
):
    url: str
    description: Optional[str]
    poster_url: Optional[str] = Field(alias="posterUrl")


class UpsertBusinessWithRelationsUpsertBusinessWithRelationsOwners(BaseModel):
    id: str
    name: str
    role: Optional[str]
    bio: Optional[str]
    media_links: Optional[
        list["UpsertBusinessWithRelationsUpsertBusinessWithRelationsOwnersMediaLinks"]
    ] = Field(alias="mediaLinks")


class UpsertBusinessWithRelationsUpsertBusinessWithRelationsOwnersMediaLinks(BaseModel):
    url: str
    description: Optional[str]
    poster_url: Optional[str] = Field(alias="posterUrl")


class UpsertBusinessWithRelationsUpsertBusinessWithRelationsExecutives(BaseModel):
    person: "UpsertBusinessWithRelationsUpsertBusinessWithRelationsExecutivesPerson"
    title: Optional[str]
    role: Optional[str]


class UpsertBusinessWithRelationsUpsertBusinessWithRelationsExecutivesPerson(BaseModel):
    id: str
    name: str
    role: Optional[str]
    bio: Optional[str]
    media_links: Optional[
        list[
            "UpsertBusinessWithRelationsUpsertBusinessWithRelationsExecutivesPersonMediaLinks"
        ]
    ] = Field(alias="mediaLinks")


class UpsertBusinessWithRelationsUpsertBusinessWithRelationsExecutivesPersonMediaLinks(
    BaseModel
):
    url: str
    description: Optional[str]
    poster_url: Optional[str] = Field(alias="posterUrl")


UpsertBusinessWithRelations.model_rebuild()
UpsertBusinessWithRelationsUpsertBusinessWithRelations.model_rebuild()
UpsertBusinessWithRelationsUpsertBusinessWithRelationsProducts.model_rebuild()
UpsertBusinessWithRelationsUpsertBusinessWithRelationsProductsCompounds.model_rebuild()
UpsertBusinessWithRelationsUpsertBusinessWithRelationsOwners.model_rebuild()
UpsertBusinessWithRelationsUpsertBusinessWithRelationsExecutives.model_rebuild()
UpsertBusinessWithRelationsUpsertBusinessWithRelationsExecutivesPerson.model_rebuild()
