# Generated by ariadne-codegen
# Source: src/graphql/operations

from typing import Any, Optional

from pydantic import Field

from .base_model import BaseModel


class UpsertDocument(BaseModel):
    upsert_document: "UpsertDocumentUpsertDocument" = Field(alias="upsertDocument")


class UpsertDocumentUpsertDocument(BaseModel):
    document_id: str = Field(alias="documentId")
    document_key: str = Field(alias="documentKey")
    type: str
    title: Optional[str]
    url: Optional[str]
    published_at: Any = Field(alias="publishedAt")
    retrieved_at: Any = Field(alias="retrievedAt")
    valid_at: Optional[Any] = Field(alias="validAt")
    invalid_at: Optional[Any] = Field(alias="invalidAt")
    expired_at: Optional[Any] = Field(alias="expiredAt")
    created_at: Any = Field(alias="createdAt")
    updated_at: Any = Field(alias="updatedAt")
    search_text: Optional[str] = Field(alias="searchText")
    search_text_embedding: Optional[list[float]] = Field(alias="searchTextEmbedding")
    search_text_model: Optional[str] = Field(alias="searchTextModel")
    search_text_version: Optional[str] = Field(alias="searchTextVersion")
    search_text_updated_at: Optional[Any] = Field(alias="searchTextUpdatedAt")
    has_text_version: Optional[list["UpsertDocumentUpsertDocumentHasTextVersion"]] = (
        Field(alias="hasTextVersion")
    )
    chunks: Optional[list["UpsertDocumentUpsertDocumentChunks"]]
    generated_by: Optional[list["UpsertDocumentUpsertDocumentGeneratedBy"]] = Field(
        alias="generatedBy"
    )


class UpsertDocumentUpsertDocumentHasTextVersion(BaseModel):
    document_text_version: (
        "UpsertDocumentUpsertDocumentHasTextVersionDocumentTextVersion"
    ) = Field(alias="documentTextVersion")
    valid_at: Optional[Any] = Field(alias="validAt")
    invalid_at: Optional[Any] = Field(alias="invalidAt")
    expired_at: Optional[Any] = Field(alias="expiredAt")
    created_at: Any = Field(alias="createdAt")


class UpsertDocumentUpsertDocumentHasTextVersionDocumentTextVersion(BaseModel):
    document_text_version_id: str = Field(alias="documentTextVersionId")
    text_version_hash: str = Field(alias="textVersionHash")
    source: str
    language: Optional[str]
    text: str
    valid_at: Optional[Any] = Field(alias="validAt")
    invalid_at: Optional[Any] = Field(alias="invalidAt")
    expired_at: Optional[Any] = Field(alias="expiredAt")
    created_at: Any = Field(alias="createdAt")
    updated_at: Any = Field(alias="updatedAt")
    search_text: Optional[str] = Field(alias="searchText")
    search_text_embedding: Optional[list[float]] = Field(alias="searchTextEmbedding")
    search_text_model: Optional[str] = Field(alias="searchTextModel")
    search_text_version: Optional[str] = Field(alias="searchTextVersion")
    search_text_updated_at: Optional[Any] = Field(alias="searchTextUpdatedAt")


class UpsertDocumentUpsertDocumentChunks(BaseModel):
    chunk: "UpsertDocumentUpsertDocumentChunksChunk"
    valid_at: Optional[Any] = Field(alias="validAt")
    invalid_at: Optional[Any] = Field(alias="invalidAt")
    expired_at: Optional[Any] = Field(alias="expiredAt")
    created_at: Any = Field(alias="createdAt")


class UpsertDocumentUpsertDocumentChunksChunk(BaseModel):
    chunk_id: str = Field(alias="chunkId")
    chunk_key: str = Field(alias="chunkKey")
    index: int
    text: str
    char_start: Optional[int] = Field(alias="charStart")
    char_end: Optional[int] = Field(alias="charEnd")
    start_ms: Optional[int] = Field(alias="startMs")
    end_ms: Optional[int] = Field(alias="endMs")
    embedding: Optional[list[float]]
    embedding_model: Optional[str] = Field(alias="embeddingModel")
    embedding_version: Optional[str] = Field(alias="embeddingVersion")
    valid_at: Optional[Any] = Field(alias="validAt")
    invalid_at: Optional[Any] = Field(alias="invalidAt")
    expired_at: Optional[Any] = Field(alias="expiredAt")
    created_at: Any = Field(alias="createdAt")
    updated_at: Any = Field(alias="updatedAt")


class UpsertDocumentUpsertDocumentGeneratedBy(BaseModel):
    research_run_ref: "UpsertDocumentUpsertDocumentGeneratedByResearchRunRef" = Field(
        alias="researchRunRef"
    )
    operation: str
    stage_key: Optional[str] = Field(alias="stageKey")
    sub_stage_key: Optional[str] = Field(alias="subStageKey")
    extractor_version: Optional[str] = Field(alias="extractorVersion")
    extracted_at: Any = Field(alias="extractedAt")
    valid_at: Optional[Any] = Field(alias="validAt")
    invalid_at: Optional[Any] = Field(alias="invalidAt")
    expired_at: Optional[Any] = Field(alias="expiredAt")
    created_at: Any = Field(alias="createdAt")


class UpsertDocumentUpsertDocumentGeneratedByResearchRunRef(BaseModel):
    research_run_ref_id: str = Field(alias="researchRunRefId")
    mongo_run_id: str = Field(alias="mongoRunId")
    label: Optional[str]
    started_at: Any = Field(alias="startedAt")
    ended_at: Any = Field(alias="endedAt")
    valid_at: Optional[Any] = Field(alias="validAt")
    invalid_at: Optional[Any] = Field(alias="invalidAt")
    expired_at: Optional[Any] = Field(alias="expiredAt")
    created_at: Any = Field(alias="createdAt")
    updated_at: Any = Field(alias="updatedAt")


UpsertDocument.model_rebuild()
UpsertDocumentUpsertDocument.model_rebuild()
UpsertDocumentUpsertDocumentHasTextVersion.model_rebuild()
UpsertDocumentUpsertDocumentChunks.model_rebuild()
UpsertDocumentUpsertDocumentGeneratedBy.model_rebuild()
