# Generated by ariadne-codegen
# Source: src/graphql/operations

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class UpsertProductWithRelations(BaseModel):
    upsert_product_with_relations: Optional[
        "UpsertProductWithRelationsUpsertProductWithRelations"
    ] = Field(alias="upsertProductWithRelations")


class UpsertProductWithRelationsUpsertProductWithRelations(BaseModel):
    id: str
    name: str
    description: Optional[str]
    price: Optional[float]
    ingredients: list[str]
    source_url: Optional[str] = Field(alias="sourceUrl")
    media_links: Optional[
        list["UpsertProductWithRelationsUpsertProductWithRelationsMediaLinks"]
    ] = Field(alias="mediaLinks")
    business: "UpsertProductWithRelationsUpsertProductWithRelationsBusiness"
    compounds: Optional[
        list["UpsertProductWithRelationsUpsertProductWithRelationsCompounds"]
    ]


class UpsertProductWithRelationsUpsertProductWithRelationsMediaLinks(BaseModel):
    url: str
    description: Optional[str]
    poster_url: Optional[str] = Field(alias="posterUrl")


class UpsertProductWithRelationsUpsertProductWithRelationsBusiness(BaseModel):
    id: str
    name: str
    description: Optional[str]
    website: Optional[str]


class UpsertProductWithRelationsUpsertProductWithRelationsCompounds(BaseModel):
    id: str
    name: str
    description: Optional[str]
    aliases: list[str]
    media_links: Optional[
        list["UpsertProductWithRelationsUpsertProductWithRelationsCompoundsMediaLinks"]
    ] = Field(alias="mediaLinks")


class UpsertProductWithRelationsUpsertProductWithRelationsCompoundsMediaLinks(
    BaseModel
):
    url: str
    description: Optional[str]
    poster_url: Optional[str] = Field(alias="posterUrl")


UpsertProductWithRelations.model_rebuild()
UpsertProductWithRelationsUpsertProductWithRelations.model_rebuild()
UpsertProductWithRelationsUpsertProductWithRelationsCompounds.model_rebuild()
