# Generated by ariadne-codegen
# Source: src/graphql/operations

from pydantic import Field

from .base_model import BaseModel


class UpsertDocumentTextVersionBundle(BaseModel):
    upsert_document_text_version_bundle: (
        "UpsertDocumentTextVersionBundleUpsertDocumentTextVersionBundle"
    ) = Field(alias="upsertDocumentTextVersionBundle")


class UpsertDocumentTextVersionBundleUpsertDocumentTextVersionBundle(BaseModel):
    document_id: str = Field(alias="documentId")
    document_text_version_id: str = Field(alias="documentTextVersionId")
    segmentation_id: str = Field(alias="segmentationId")
    chunk_metas: list[
        "UpsertDocumentTextVersionBundleUpsertDocumentTextVersionBundleChunkMetas"
    ] = Field(alias="chunkMetas")
    next_chunk_edges_created: bool = Field(alias="nextChunkEdgesCreated")


class UpsertDocumentTextVersionBundleUpsertDocumentTextVersionBundleChunkMetas(
    BaseModel
):
    chunk_id: str = Field(alias="chunkId")
    chunk_key: str = Field(alias="chunkKey")
    index: int


UpsertDocumentTextVersionBundle.model_rebuild()
UpsertDocumentTextVersionBundleUpsertDocumentTextVersionBundle.model_rebuild()
