# Generated by ariadne-codegen
# Source: src/graphql/operations

from typing import Literal, Optional, Union

from pydantic import Field

from .base_model import BaseModel
from .enums import EvidenceEdgeType, EvidenceSourceKind


class UpsertEvidenceEdge(BaseModel):
    upsert_evidence_edge: "UpsertEvidenceEdgeUpsertEvidenceEdge" = Field(
        alias="upsertEvidenceEdge"
    )


class UpsertEvidenceEdgeUpsertEvidenceEdge(BaseModel):
    ok: bool
    edge_type: EvidenceEdgeType = Field(alias="edgeType")
    rel_key: str = Field(alias="relKey")
    relationship_id: Optional[str] = Field(alias="relationshipId")
    source: Union[
        "UpsertEvidenceEdgeUpsertEvidenceEdgeSourceEvidenceSourceRefDocumentResult",
        "UpsertEvidenceEdgeUpsertEvidenceEdgeSourceEvidenceSourceRefChunkResult",
    ] = Field(discriminator="typename__")
    target: "UpsertEvidenceEdgeUpsertEvidenceEdgeTarget"
    created: bool
    updated: bool


class UpsertEvidenceEdgeUpsertEvidenceEdgeSourceEvidenceSourceRefDocumentResult(
    BaseModel
):
    typename__: Literal["EvidenceSourceRefDocumentResult"] = Field(alias="__typename")
    kind: EvidenceSourceKind
    document_id: str = Field(alias="documentId")


class UpsertEvidenceEdgeUpsertEvidenceEdgeSourceEvidenceSourceRefChunkResult(BaseModel):
    typename__: Literal["EvidenceSourceRefChunkResult"] = Field(alias="__typename")
    kind: EvidenceSourceKind
    chunk_id: str = Field(alias="chunkId")


class UpsertEvidenceEdgeUpsertEvidenceEdgeTarget(BaseModel):
    node_id: str = Field(alias="nodeId")
    label: str
    unique_key: Optional[str] = Field(alias="uniqueKey")
    unique_key_value: Optional[str] = Field(alias="uniqueKeyValue")


UpsertEvidenceEdge.model_rebuild()
UpsertEvidenceEdgeUpsertEvidenceEdge.model_rebuild()
