# Generated by ariadne-codegen
# Source: src/graphql/operations

from typing import Any, Optional

from pydantic import Field

from .base_model import BaseModel


class UpsertResearchPlanRef(BaseModel):
    upsert_research_plan_ref: "UpsertResearchPlanRefUpsertResearchPlanRef" = Field(
        alias="upsertResearchPlanRef"
    )


class UpsertResearchPlanRefUpsertResearchPlanRef(BaseModel):
    research_plan_ref_id: str = Field(alias="researchPlanRefId")
    mongo_plan_id: str = Field(alias="mongoPlanId")
    label: Optional[str]
    version: Optional[str]
    valid_at: Optional[Any] = Field(alias="validAt")
    invalid_at: Optional[Any] = Field(alias="invalidAt")
    expired_at: Optional[Any] = Field(alias="expiredAt")
    created_at: Any = Field(alias="createdAt")
    updated_at: Any = Field(alias="updatedAt")


UpsertResearchPlanRef.model_rebuild()
