# Generated by ariadne-codegen
# Source: src/graphql/operations

from typing import Literal, Optional, Union

from pydantic import Field

from .base_model import BaseModel
from .enums import EvidenceEdgeType, EvidenceSourceKind


class UpsertEvidenceEdges(BaseModel):
    upsert_evidence_edges: list["UpsertEvidenceEdgesUpsertEvidenceEdges"] = Field(
        alias="upsertEvidenceEdges"
    )


class UpsertEvidenceEdgesUpsertEvidenceEdges(BaseModel):
    ok: bool
    counts: "UpsertEvidenceEdgesUpsertEvidenceEdgesCounts"
    results: list["UpsertEvidenceEdgesUpsertEvidenceEdgesResults"]
    errors: list["UpsertEvidenceEdgesUpsertEvidenceEdgesErrors"]


class UpsertEvidenceEdgesUpsertEvidenceEdgesCounts(BaseModel):
    received: int
    attempted: int
    created: int
    updated: int
    failed: int


class UpsertEvidenceEdgesUpsertEvidenceEdgesResults(BaseModel):
    ok: bool
    edge_type: EvidenceEdgeType = Field(alias="edgeType")
    rel_key: str = Field(alias="relKey")
    relationship_id: Optional[str] = Field(alias="relationshipId")
    source: Union[
        "UpsertEvidenceEdgesUpsertEvidenceEdgesResultsSourceEvidenceSourceRefDocumentResult",
        "UpsertEvidenceEdgesUpsertEvidenceEdgesResultsSourceEvidenceSourceRefChunkResult",
    ] = Field(discriminator="typename__")
    target: "UpsertEvidenceEdgesUpsertEvidenceEdgesResultsTarget"
    created: bool
    updated: bool


class UpsertEvidenceEdgesUpsertEvidenceEdgesResultsSourceEvidenceSourceRefDocumentResult(
    BaseModel
):
    typename__: Literal["EvidenceSourceRefDocumentResult"] = Field(alias="__typename")
    kind: EvidenceSourceKind
    document_id: str = Field(alias="documentId")


class UpsertEvidenceEdgesUpsertEvidenceEdgesResultsSourceEvidenceSourceRefChunkResult(
    BaseModel
):
    typename__: Literal["EvidenceSourceRefChunkResult"] = Field(alias="__typename")
    kind: EvidenceSourceKind
    chunk_id: str = Field(alias="chunkId")


class UpsertEvidenceEdgesUpsertEvidenceEdgesResultsTarget(BaseModel):
    node_id: str = Field(alias="nodeId")
    label: str
    unique_key: Optional[str] = Field(alias="uniqueKey")
    unique_key_value: Optional[str] = Field(alias="uniqueKeyValue")


class UpsertEvidenceEdgesUpsertEvidenceEdgesErrors(BaseModel):
    index: int
    edge_type: Optional[EvidenceEdgeType] = Field(alias="edgeType")
    message: str
    code: Optional[str]


UpsertEvidenceEdges.model_rebuild()
UpsertEvidenceEdgesUpsertEvidenceEdges.model_rebuild()
UpsertEvidenceEdgesUpsertEvidenceEdgesResults.model_rebuild()
